export default [
  { country: "Australia", code: "AUD", flag: "🇦🇺" },
  { country: "Brazil", code: "BRL", flag: "🇧🇷" },
  { country: "Bulgaria", code: "BGN", flag: "🇧🇬" },
  { country: "Canada", code: "CAD", flag: "🇨🇦" },
  { country: "China", code: "CNY", flag: "🇨🇳" },
  { country: "Denmark", code: "DKK", flag: "🇩🇰" },
  { country: "EMU", code: "EUR", flag: "🇪🇺" },
  { country: "Hongkong", code: "HKD", flag: "🇭🇰" },
  { country: "Hungary", code: "HUF", flag: "🇭🇺" },
  { country: "Iceland", code: "ISK", flag: "🇮🇸" },
  { country: "IMF", code: "XDR", flag: "🏛️" },
  { country: "India", code: "INR", flag: "🇮🇳" },
  { country: "Indonesia", code: "IDR", flag: "🇮🇩" },
  { country: "Israel", code: "ILS", flag: "🇮🇱" },
  { country: "Japan", code: "JPY", flag: "🇯🇵" },
  { country: "Malaysia", code: "MYR", flag: "🇲🇾" },
  { country: "Mexico", code: "MXN", flag: "🇲🇽" },
  { country: "New Zealand", code: "NZD", flag: "🇳🇿" },
  { country: "Norway", code: "NOK", flag: "🇳🇴" },
  { country: "Philippines", code: "PHP", flag: "🇵🇭" },
  { country: "Poland", code: "PLN", flag: "🇵🇱" },
  { country: "Romania", code: "RON", flag: "🇷🇴" },
  { country: "Singapore", code: "SGD", flag: "🇸🇬" },
  { country: "South Africa", code: "ZAR", flag: "🇿🇦" },
  { country: "South Korea", code: "KRW", flag: "🇰🇷" },
  { country: "Sweden", code: "SEK", flag: "🇸🇪" },
  { country: "Switzerland", code: "CHF", flag: "🇨🇭" },
  { country: "Thailand", code: "THB", flag: "🇹🇭" },
  { country: "Turkey", code: "TRY", flag: "🇹🇷" },
  { country: "United Kingdom", code: "GBP", flag: "🇬🇧" },
  { country: "USA", code: "USD", flag: "🇺🇸" },
  { country: "Czech Republic", code: "CZK", flag: "🇨🇿" },
];
